CREATE TABLE wpppm_hello (
  id INT NOT NULL AUTO_INCREMENT,
  type VARCHAR(45) NULL,
  datetime DATETIME NOT NULL,
  PRIMARY KEY (id));

CREATE TABLE wpppm_goodbye (
  id INT NOT NULL AUTO_INCREMENT,
  type VARCHAR(45) NULL,
  datetime DATETIME NOT NULL,
  PRIMARY KEY (id));