CREATE TABLE rendezvous (
  id INT NOT NULL AUTO_INCREMENT,
  type VARCHAR(45) NULL,
  datetime DATETIME NOT NULL,
  PRIMARY KEY (id));

CREATE TABLE test2 (
  id INT NOT NULL AUTO_INCREMENT,
  type VARCHAR(45) NULL,
  datetime DATETIME NOT NULL,
  PRIMARY KEY (id));